import "../styles/globals.css";
import Navigation from "../components/Navigation";

export const metadata = {
  title: "Blog Cyprien",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <Navigation />
    </header>
  );

  return (
    <html lang='en'>
      <body>
        <div className='mx-auto w-full'>
          {header}
          {children}
        </div>
      </body>
    </html>
  );
}
